name: Sanity Build

on: 
  push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install  # Ensures all dependencies are installed

      # Run Cypress using GitHub Action
      - name: Run Cypress Register Test
        uses: cypress-io/github-action@v5
        with:
          browser: firefox
          spec: "cypress/e2e/tests/registerTest.cy.js"
