name: Sanity Build

on:
  push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install # Ensures all dependencies are installed

      # Run Cypress using GitHub Action
      - name: Run Cypress Register Test
        uses: cypress-io/github-action@v5
        with:
          name: Mochaawesome HTML Report – Add To Cart
          path: cypress/reports/html

      # Upload the Cypress Test Report
      - name: Upload Cypress Report
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome-HTML-Report
          path: cypress/reports/html
