name: Sanity Build

on: 
  push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install  # Ensures all dependencies are installed

      # Run only the specified test suite
      - name: Run Cypress Register Test
        run: npx cypress run --spec "cypress/e2e/tests/registerTest.cy.js"
        with:
         browser: firefox

