name: Sanity Build

on: 
  push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install  # Ensures all dependencies are installed

      # Run only the specified test suite
      - name: Run Cypress Register Test
        run: npm run test:registertest  # ✅ This ensures only the specified test runs
